spring.application.name=springREST

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=scott
spring.datasource.password=tiger

#ddl_auto
#   create : SessionFactory; //시작시 스키마를 삭제하고 재생성
#   create-drop : SessionFactory; //종료시에 스키마를 삭제함
#   update : SessionFactory
#   validate : SessionFactory //접속스키마와 다를 경우 예외처리
#   none : 아무것도 안함 //서비스가 돌고 있을 경우
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#application.properties가 하는 역할
#