spring.application.name=springREST

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oraclejava

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update